{"uuid": "f7ebf43f-c14f-4563-a30d-a30f88269f59", "children": ["fdb796a2-eefe-4db3-afb7-e76b47077c3e", "072abecd-3e44-4ab2-aee0-935a82a6fd20", "27323b1d-9868-4a47-8eea-b39bbf440269", "538f9983-5ec0-4cbe-9cfb-0700df893990", "4fb1758b-0b4e-4373-8216-1ed5ddc1f7c2", "fa37d472-0e75-4733-a36a-7b4ea8fdee43", "01a8c89f-2c83-4e66-8b59-5eb4c8fa0e13", "e0776dd7-8118-4144-82be-9aa1ac204232"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions\nfrom invalid argument: unrecognized chrome option: prefs\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6dc05fe75+79173]\n\tGetHandleVerifier [0x0x7ff6dc05fed0+79264]\n\t(No symbol) [0x0x7ff6dbe19e5a]\n\t(No symbol) [0x0x7ff6dbe48f53]\n\t(No symbol) [0x0x7ff6dbe4aa58]\n\t(No symbol) [0x0x7ff6dbe44f0a]\n\t(No symbol) [0x0x7ff6dbea49a2]\n\t(No symbol) [0x0x7ff6dbea42b7]\n\t(No symbol) [0x0x7ff6dbea61c0]\n\t(No symbol) [0x0x7ff6dbea5f70]\n\t(No symbol) [0x0x7ff6dbe98743]\n\t(No symbol) [0x0x7ff6dbe614c1]\n\t(No symbol) [0x0x7ff6dbe62253]\n\tGetHandleVerifier [0x0x7ff6dc32a2ad+3004797]\n\tGetHandleVerifier [0x0x7ff6dc3246fd+2981325]\n\tGetHandleVerifier [0x0x7ff6dc343350+3107360]\n\tGetHandleVerifier [0x0x7ff6dc07a9fe+188622]\n\tGetHandleVerifier [0x0x7ff6dc08228f+219487]\n\tGetHandleVerifier [0x0x7ff6dc068dc4+115860]\n\tGetHandleVerifier [0x0x7ff6dc068f79+116297]\n\tGetHandleVerifier [0x0x7ff6dc04f528+11256]\n\tBaseThreadInitThunk [0x0x7ff914f07374+20]\n\tRtlUserThreadStart [0x0x7ff9162dcc91+33]\n\n", "trace": "  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\Example\\Notes\\PlanSource_Test_Automation\\test_pages\\conftest.py\", line 34, in driver\n    driver = webdriver.Chrome(options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750163995637, "stop": 1750163998461}], "start": 1750163995637, "stop": 1750163999259}