{"uuid": "3639a185-fb63-4009-9e88-497d28a8011f", "children": ["4e1c33dd-943d-4dd7-8e69-45744eff7ace", "85de5df0-762c-46b6-90ec-eb756dbf7b95", "556ff9f7-7528-4c4a-85ea-68ff92011f21", "53b86ab3-0595-4337-8f4b-c84e53a738aa", "7c0ee682-4d81-440d-b956-1072c5b2d877", "b656c137-6586-4526-80a9-da9fb73914da", "e9c99b5e-f910-4150-8125-03ce11777f87", "1288c403-cb31-4844-97a2-4afabb94787f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: goog:chromeOptions\nfrom invalid argument: unrecognized chrome option: prefs\nStacktrace:\n\tGetHandleVerifier [0x0xc73783+63299]\n\tGetHandleVerifier [0x0xc737c4+63364]\n\t(No symbol) [0x0xaa1113]\n\t(No symbol) [0x0xac87dc]\n\t(No symbol) [0x0xaca0c0]\n\t(No symbol) [0x0xac524d]\n\t(No symbol) [0x0xb18c62]\n\t(No symbol) [0x0xb18746]\n\t(No symbol) [0x0xb19eaf]\n\t(No symbol) [0x0xb19c5a]\n\t(No symbol) [0x0xb0e376]\n\t(No symbol) [0x0xadd6e0]\n\t(No symbol) [0x0xade544]\n\tGetHandleVerifier [0x0xece073+2531379]\n\tGetHandleVerifier [0x0xec9372+2511666]\n\tGetHandleVerifier [0x0xc99efa+220858]\n\tGetHandleVerifier [0x0xc8a548+156936]\n\tGetHandleVerifier [0x0xc90c7d+183357]\n\tGetHandleVerifier [0x0xc7b6e8+95912]\n\tGetHandleVerifier [0x0xc7b890+96336]\n\tGetHandleVerifier [0x0xc6666a+9770]\n\tBaseThreadInitThunk [0x0x7608fcc9+25]\n\tRtlGetAppContainerNamedObjectPath [0x0x77c882ae+286]\n\tRtlGetAppContainerNamedObjectPath [0x0x77c8827e+238]\n\n", "trace": "  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\Example\\Notes\\PlanSource_Test_Automation\\test_pages\\conftest.py\", line 33, in driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Pawan.Pawar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750163704825, "stop": 1750163709051}], "start": 1750163704825, "stop": 1750163709803}